[firebase]
type = "service_account"
project_id = "hasar-organization"
private_key_id = "64dc98de39b36af2f35dd54b48ecfd86970b34d0"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCe45CgLDSI0rEB
13byuBRDVWca6JG7WpVjkv8wxJAfo0cig5Xa+R17grjYLSce85CiTeo19BGpKyVn
42KAIsZ5itgB9OSuH41d7+lH/Qq+CAJ4HNQktoFVwYml5LgxWgPMlvs5otQqU27G
5cAb/B45d3bjcUZv9inZEAKSSlQ47SyCZp561qZapsWt0WcsVoQ0pk8ITAQ4mfWM
VgDM/aLkkLsc0CXCLz73zGViuClBempYS/IZ9UeZ09HpWsx+T2+oEIsLybNNSzhT
CKLwMLrOBJ9fa68b/uR1RAOrq7hqBMYyGgPGF4Q6dG9m/KycmQgIIJD81XN9alFD
Sh+8fEAfAgMBAAECggEAAZMXfHy8MZxBtZtc45smmVKgAkioRdyBrjk0K88m3fQQ
aZp7bQf4kaAbvzz0YVxo0zDN8ciIv3iP/Wbn3lJGs+q23DnWQ2LzU9PsJ8YT6/mm
ensLdQZ7liu1OvgJsA4u1/0hLltOmmstP5hqvksv26ARL9Ep04jicYyjvAR3wO+V
1qiiH17v9CY2Ch5ONsc3Fdl8ZnvjSqMthNLNakTlyZ2ZXgYtAr6buiyX4EPhBrG0
/Ai11uADFozEGkQO3aTwCq8oKATpQPcTXlMxkAEVyONGDAJntWmGsRHAODDECvZ6
rVfJlaeeNqBBKP2t+vXb2xs2w4ptML6lmoc1/Mls0QKBgQDK1sHGebn/47VTameo
rIrewz0Dgo25cj8oqD1HDb2sl01ozQrRjJiIhydiMhGKpWvYjX8zgbl+fhzQdHC3
SOE9H8zJTvpqnQsdLdnfH9IaX3odrH62ebJwwFfMLQ1KWKgXbt0jfM48Y/VJvagG
qLBR21SK61cYvNpqFxdd3fcuVQKBgQDIiAkF1NzMWX/Z4P9YUt/8lN8hzg1EXb2z
nHD6Y5L6aLqNKkSvPceqnzAbteyWjYZ4nWgY5DxF6tfA7oSfz5oZqinvk2UygY5V
4FK0d+ztHyHeAcqogW/9zJvS34L00rhFnaKFiCRiwWUccjyCl9eE+FhLTWlBEE0S
fRN+VfLAowKBgQCCI8evz+nGhBKSsnJPhmSTCDDdT6YelW5wZ4DpVaecVHcWBngq
ekpjTlO2bOlUS04mYqJ6KYEZ51AVbp/i+J+K2BxMDKAeRyQaVJC013W19gwjfcjO
ysXyEXZDSaR9TuSKJFc9rZWkqX13Enf7zb9SxaY4e0YmWQTJjIcxcnhlAQKBgBHE
s//3R4U33PNCU33RAhXQXyEQr+5B3CBBGWWmUwyrIPSHLUTV1Y5RwqKB8S+55JNl
Zyblek27rFhlCg1bCM2DXWnkBpB+GE2Vrd5dzfmIy6hvQjTCG1lCuv/pXCIzVa6d
dBwe3xJ9DmeB28i6iZc3piMt/ciNGDcuK/8CwJq/AoGAAw8bNMigDi9ctcw8PnM3
27UuBF8dfu/9A7qn9JZL8hVHZvtBahC7bXB203WL6CMpLM35dj/dLi8eeAz/TvEa
JbSjdc1Qq4LYqrW39rl9Tgn8do+ZYQcTwUts1XEbwymbeRGwKBoEdC7RjG1vKRem
ww3nSKOaKzMuKcJFR9wTp/I=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@hasar-organization.iam.gserviceaccount.com"
client_id = "114585462231801286212"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40hasar-organization.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
