[firebase]
type = "service_account"
project_id = "hasar-organization"
private_key_id = "dd911746ca89d1127d3e47fda102ec301e68a038"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDNMFOiShMInmN7
mf4ZzGVcc+TjeRyOvHgFfksccsD+Mv753vf73ud4pHdqZU1DvUVSOONzbGqVxW3w
c5cWuityjVJP7FVSqLJIcFYKscAeYk59WfnXd2V3Y898FL3VFLVH1Veq1lIqqzgA
TwW49+OxMva3tczNk9wzhrQ13/BwI2gmO66zQP6rgTFhLgJ78lMU/SQk5zuVsndw
dJ4LNG2HbRl0JFeXaw/rQxYsQoZPwDTTH4A3Mew52Q5YHk4dhPMsK5rgvJHSJSUL
7xsPEdd7Sy6k1oWzrPmeNu1ckPRsi/Fy5QfentghiB4MzdypqWsv+2IZ1apV3GQo
XjSbGKwVAgMBAAECggEAJDg6IyUhO/29gNV7gbFPWSUKC89Wp6mEJDAZcSGeiKCW
2qOtsZO011psy+aq32C7KlrpZ3gFTn/FutKkonnlbnicxYfpvcgShG/z+DpNN+/R
fBYUYKDuU8dWGkiNA95+a3ow2fKwGWEU5xUL5Q0475AX9fDNAKLvlVbbW8E2b4y3
F8kS6A6M+GfT7CLmqwinIqUT+eG0OgxfSPCQ3A+xjFr/2kYcbs3G0Vj0WpyOnlRO
S76qwvue/05ZMOGfUnwnIJSeugbT7QY5qtz0KnQOiHibPBLFmjBFKTYPXOlr+w3R
qsFs95TBZM14x+cdnJa8tvh61HGOda9fmkhT8+4k0QKBgQD+7pdT55r/bRe9sUX1
zUPcYdWq9tpDAUlZoqWawjuJE/cIY2IZItk6LtPacszCaoI7tbBkoeCPOS9/O1xt
IQPLp1uU4fcq8rxxgYicWU0gcoeORPQpvw4BGL0Wy0emWWDYs3mtUJU5qhmFmlau
1nJOFxES6Zqmwu7NCoEyZ6VJHQKBgQDODGMXgluhujTSXfo+c7j7d7MjYuyPhDW/
XH0x8PxlvSwKVQntLV1i59h/LB+qwmbMZu++aqfVQOU1PbvYHDdL0PyEpcn4+NT5
fRZJnQjF8AJ9lWziGk9BEmk3tCIgu6QrwUPcCCQKqk9H8cPmbqRegZesO1HXm/Xf
CzAb65h1WQKBgBUdRcNZR2koa/L2H8k/+wLhx4SldWZfUOfvpK+wrqWn1aoIMTPL
wxoijsFlCLiBgc/YOIfdMHAsWFa9X+ZZ+aqAbgFixcn02M6938azTsQFOFz8MQzU
GiDVH7QnmgOZG4BXPRixt+pSwFJkehF5CXaWSn+6gWiWdJje6dx24SWxAoGAClZk
wlEv97U34TYF0AxOQ4+F1UipRaoEaE1jmpXUk+Yhx4LstJGKFeQ74GV+UTrfnXGs
pYkEUpam6Tznp7gCrjMV+DG5KFyTktDLxXWzcvrPpS1SASYAw+sAjGLlM282lVtk
5C0kYcSZpapjgbQbWwJ1cZaoTIDunPoat8viIkECgYAYPTQ3CcyuSuwH0Y7mGQnk
HFRnnw0lZrobqWWzG1vfhY2+5XIx9xkFOEgaHuN1LAmQC+qH5GKiC3UzVjTFW6UC
Ax7tlZd8zm4XdSS7dXP8QYyT2qUkiYydVN+i40Dgx0jY85fYHztuTxp01HC8Z1Uc
DnBDNH6zY5hyQl2zandoRQ==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@hasar-organization.iam.gserviceaccount.com"
client_id = "114585462231801286212"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40hasar-organization.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

FIREBASE_API_KEY = "AIzaSyANsvS9d7Vcw-pvJeIupLbBH-wDXw1BgjE"
