[firebase]
type = "service_account"
project_id = "hasar-organization"
private_key_id = "69ccf45b3c5be64044d42f7f1c50665af4c0a423"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfz+lRnZT8hwtA
dj34hbdXI1b5vLisOyDlUmniyZkJYJ5Km4XrOm7oOfqDkDdPcINKd3ljmuFx/c6Y
NYneaAqNMC5y22DLpeJ4UuDf9eoEbiyFqCi3n7giI35qrMKWUmUEEzEaHCcMDs+1
L+0WbbiGY8t9R+gx03mQQbNJ2GfMJIDB25tzPXQ50g/35nuNgiWbm+kv5zX73UjZ
ttxRVA8/uskaeJ9EqKK52hiPk/LhOgzhDDogNI1jdtDhvRoU7MYorjM6YuTR/47Z
43o8wZNwPaKJfiSDQtlsQlALxilHBYS63h0UmuVGJrZBVPXmBuuVlYA76HX5Eg2C
a1//35UPAgMBAAECggEABm06gUU4hhU6LxvyLwnVjyQFLeLYfFieYIp5Zpzb0iQ4
CWEKuCRv7FfUirDkgIXSSc7XK1nBoi9mPPm+Mxr0/auH2qeW02m220bd8zO09vul
P7S8+nFqWrkZrtmGs7vZgxnweg/SxCneUXd9bc74wjLGLqITJNnPxCzYNGqG9g8b
dfBTb3O431Xoh/lmUy4wXaSlxCAX7V84+o5lWNxpqZ7dcLOgGx2TzsR5IpJbRe6v
RhsAwrA3HcoHYZv4uzj2fGev6FWpnBQvyL0V/tgY3SPaFpIORRMN2Y0tNkpoXA8P
MOX6ctUz+Q7ltdHLIlCUCKDxWgUNPlHenpqGP7mDPQKBgQDQZTNwmv6BzURZNbfY
ICdCNjpA+N//Nl2kXmn0oa6ZvKlbF2JQBMFkMf7Xq0BcGXkrBecabTVcX5B0I07c
3gTT56TteaX1W0JSHt5/L0JgMeFEfRKTJmlMXmcyOkfu/SqGM3O8Pvx7aHC66jHw
B78pc4gVGfArKHdyKasFcnkPYwKBgQDEUZqtg2IHpHnpR7/45f7ljJ9xpaFczaS2
0CkF3se+2ItgjWbBml3zdc+CdC9GhLv09qft8oaRhMjEndskq0FWzUhhSeLfRHFj
TO3jaDZUGdEmfqMlC1JlBi3+7rgbEBFdoOWoZJZSVX3DUiJMhg+UjnUpLnYOjg4n
tbIjQhhhZQKBgQC7zLeSntsEtqsFifdneXJnpN7SdnXGVIQHAF6T6rCiMvab9HLQ
kbiGRtfWG6ogVYRwVR1zHz+bQzO2tar4N8w5+uMSbzIz7k3SG6d/DmPOtKTBR8VZ
fqAeBmURSpxQry2HSw7dchWuUOxmRW9DVHfdLxRPj9Rz0D/0TcClZAfc6QKBgFNW
xQ/1ny7ZXrtuLwuNL2jpCmKnSlnoHo1QzqlkSm005e4F+OIlEs8gawfZJJyOCnBS
KTW05/VsZgI5dOcbIDCmEpziTcIz/uKFrNMF0VJgZ04tIjq+lKq4NdxsIJG0f3q8
q+GRWdL34dyByHetzX1mAEyMIafKHC41Trry+wCVAoGAaYVzUbMW52vhxf7ras4p
Se78zB5Exa+x5boJ2JsVugoHB5Fc8cdKsCdtFR0beEHFp5pntJupSJkM5DplmMOk
m2afm3lps485RO2VfwbsvMi5TsZGuqaD6aioVtKQGVgCDdwPH6/ImsiMwXUzKaQy
GsPKJQ/JYR1htUtCr/R88+s=
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@hasar-organization.iam.gserviceaccount.com"
client_id = "114585462231801286212"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40hasar-organization.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
FIREBASE_API_KEY = "AIzaSyANsvS9d7Vcw-pvJeIupLbBH-wDXw1BgjE"
